version: '3.8' # Upgraded from '3' to support 'service_healthy'
services:
  backend:
    image: abhay0263/tic-tac-toe-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - my-net2
    depends_on:
      db2:
        condition: service_healthy # Wait for the healthcheck to pass

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - my-net2

  db2:
    image: mysql:8
    container_name: db2
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-net2
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  my-net2:
    driver: bridge

volumes:
  db_data:
